config/routes.rb
Rails.application.routes.draw do
  resources :voyages
  resources :marques
  resources :personnes
  get '/voitures/recherche/:immatriculation', to: 'voitures#recherche', as: 'recherche'
  resources :voitures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/personne.rb
class Personne < ApplicationRecord

  has_many :voitures
  has_and_belongs_to_many :voyages

  def age
    ((Date.today - date_naissance)/365.25).floor
  end

  def nom_complet
    prenom + " " + nom
  end

end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render :show, status: :created, location: @personne }
      else
        format.html { render :new }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { render :show, status: :ok, location: @personne }
      else
        format.html { render :edit }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url, notice: 'Personne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.require(:personne).permit(:nom, :prenom, :date_naissance, voyage_ids: [])
    end
end

app/helpers/personnes_helper.rb
module PersonnesHelper
end

app/views/personnes/_form.html.erb
<%= form_for(personne) do |f| %>
  <% if personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
      <% personne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>

  <div class="field">
    <%= f.label :prenom %>
    <%= f.text_field :prenom %>
  </div>

  <div class="field">
    <%= f.label :date_naissance %>
    <%= f.date_select :date_naissance %>
  </div>

  <div class="field">
    <%= f.label :voyage_ids %>
    <%= f.collection_select :voyage_ids, Voyage.all, :id, :voyage,  {}, {:multiple => true}  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnes/edit.html.erb
<h1>Editing Personne</h1>

<%= render 'form', personne: @personne %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

app/views/personnes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personnes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Date naissance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnes.each do |personne| %>
      <tr>
        <td><%= personne.nom %></td>
        <td><%= personne.prenom %></td>
        <td><%= personne.date_naissance %></td>
        <td><%= link_to 'Show', personne %></td>
        <td><%= link_to 'Edit', edit_personne_path(personne) %></td>
        <td><%= link_to 'Destroy', personne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personne', new_personne_path %>

app/views/personnes/new.html.erb
<h1>New Personne</h1>

<%= render 'form', personne: @personne %>

<%= link_to 'Back', personnes_path %>

app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @personne.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @personne.prenom %>
</p>

<p>
  <strong>Date naissance:</strong>
  <%= @personne.date_naissance %>
</p>

<fieldset>
  <% @personne.voitures.each do |voiture| %>
    <%= render partial: "/voitures/voiture_view", locals: {voiture: voiture} %>
  <% end %>
</fieldset>


<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>