config/routes.rb
Rails.application.routes.draw do
  resources :voyages
  resources :marques
  resources :personnes
  get '/voitures/recherche/:immatriculation', to: 'voitures#recherche', as: 'recherche'
  resources :voitures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/voyage.rb
class Voyage < ApplicationRecord
  has_and_belongs_to_many :personnes

  def voyage
  	depart + " - " + arrivee
  end
  
end

app/controllers/voyages_controller.rb
class VoyagesController < ApplicationController
  before_action :set_voyage, only: [:show, :edit, :update, :destroy]

  # GET /voyages
  # GET /voyages.json
  def index
    @voyages = Voyage.all
  end

  # GET /voyages/1
  # GET /voyages/1.json
  def show
  end

  # GET /voyages/new
  def new
    @voyage = Voyage.new
  end

  # GET /voyages/1/edit
  def edit
  end

  # POST /voyages
  # POST /voyages.json
  def create
    @voyage = Voyage.new(voyage_params)

    respond_to do |format|
      if @voyage.save
        format.html { redirect_to @voyage, notice: 'Voyage was successfully created.' }
        format.json { render :show, status: :created, location: @voyage }
      else
        format.html { render :new }
        format.json { render json: @voyage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voyages/1
  # PATCH/PUT /voyages/1.json
  def update
    respond_to do |format|
      if @voyage.update(voyage_params)
        format.html { redirect_to @voyage, notice: 'Voyage was successfully updated.' }
        format.json { render :show, status: :ok, location: @voyage }
      else
        format.html { render :edit }
        format.json { render json: @voyage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voyages/1
  # DELETE /voyages/1.json
  def destroy
    @voyage.destroy
    respond_to do |format|
      format.html { redirect_to voyages_url, notice: 'Voyage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voyage
      @voyage = Voyage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voyage_params
      params.require(:voyage).permit(:depart, :arrivee, personne_ids: [])
    end
end

app/helpers/voyages_helper.rb
module VoyagesHelper
end

app/views/voyages/_form.html.erb
<%= form_for(voyage) do |f| %>
  <% if voyage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voyage.errors.count, "error") %> prohibited this voyage from being saved:</h2>

      <ul>
      <% voyage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :depart %>
    <%= f.text_field :depart %>
  </div>

  <div class="field">
    <%= f.label :arrivee %>
    <%= f.text_field :arrivee %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voyages/edit.html.erb
<h1>Editing Voyage</h1>

<%= render 'form', voyage: @voyage %>

<%= link_to 'Show', @voyage %> |
<%= link_to 'Back', voyages_path %>

app/views/voyages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voyages</h1>

<table>
  <thead>
    <tr>
      <th>Depart</th>
      <th>Arrivee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voyages.each do |voyage| %>
      <tr>
        <td><%= voyage.depart %></td>
        <td><%= voyage.arrivee %></td>
        <td><%= link_to 'Show', voyage %></td>
        <td><%= link_to 'Edit', edit_voyage_path(voyage) %></td>
        <td><%= link_to 'Destroy', voyage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voyage', new_voyage_path %>

app/views/voyages/new.html.erb
<h1>New Voyage</h1>

<%= render 'form', voyage: @voyage %>

<%= link_to 'Back', voyages_path %>

app/views/voyages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Depart:</strong>
  <%= @voyage.depart %>
</p>

<p>
  <strong>Arrivee:</strong>
  <%= @voyage.arrivee %>
</p>

<%= link_to 'Edit', edit_voyage_path(@voyage) %> |
<%= link_to 'Back', voyages_path %>