config/routes.rb
Rails.application.routes.draw do
  resources :voyages
  resources :marques
  resources :personnes
  get '/voitures/recherche/:immatriculation', to: 'voitures#recherche', as: 'recherche'
  resources :voitures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/voiture.rb
class Voiture < ApplicationRecord
  
  belongs_to :personne, required: false
  belongs_to :marque, required: false

  def age
    ((Date.today - date_mise_en_service)/365.25).floor
  end

 
end

app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  before_action :set_voiture, only: [:show, :edit, :update, :destroy]

  # GET /voitures
  # GET /voitures.json
  def index
    @voitures = Voiture.all
  end

  # GET /voitures/1
  # GET /voitures/1.json
  def show
  end

  # GET /voitures/new
  def new
    @voiture = Voiture.new
  end

  # GET /voitures/1/edit
  def edit
  end

  # POST /voitures
  # POST /voitures.json
  def create
    @voiture = Voiture.new(voiture_params)

    respond_to do |format|
      if @voiture.save
        format.html { redirect_to @voiture, notice: 'Voiture was successfully created.' }
        format.json { render :show, status: :created, location: @voiture }
      else
        format.html { render :new }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voitures/1
  # PATCH/PUT /voitures/1.json
  def update
    respond_to do |format|
      if @voiture.update(voiture_params)
        format.html { redirect_to @voiture, notice: 'Voiture was successfully updated.' }
        format.json { render :show, status: :ok, location: @voiture }
      else
        format.html { render :edit }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voitures/1
  # DELETE /voitures/1.json
  def destroy
    @voiture.destroy
    respond_to do |format|
      format.html { redirect_to voitures_url, notice: 'Voiture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recherche
    @recherche = Voiture.where(immatriculation: params[:immatriculation]).first
    respond_to do |format|
      if @recherche
        format.html { redirect_to @recherche, notice: 'Voiture trouvée.' }
        format.json { render :recherche, status: :ok, location: @recherche}
      else
        format.html { redirect_to voitures_url}
        format.json { render json: @recherche.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voiture
      @voiture = Voiture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwi6vd2Oh9bSAhUCshQKHWlxC94QFggcMAA&url=http%3A%2F%2Fblog.bigbinary.com%2F2016%2F02%2F29%2Frails-5-improves-redirect_to_back-with-redirect-back.html&usg=AFQjCNGl7Kn1bOUR9ZG3-_pncMjvI6gc0w&sig2=4yviC1nkcslSAlHmNd2fPQ
    def voiture_params
      params.require(:voiture).permit(:immatriculation, :couleur, :modele, :date_mise_en_service, :personne_id, :marque_id)
    end
end

app/helpers/voitures_helper.rb
module VoituresHelper
end

app/views/voitures/_form.html.erb
<%= form_for(voiture) do |f| %>
  <% if voiture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voiture.errors.count, "error") %> prohibited this voiture from being saved:</h2>

      <ul>
      <% voiture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :immatriculation %>
    <%= f.text_field :immatriculation %>
  </div>

  <div class="field">
    <%= f.label :couleur %>
    <%= f.text_field :couleur %>
  </div>

  <div class="field">
    <%= f.label :modele %>
    <%= f.text_field :modele %>
  </div>

  <div class="field">
    <%= f.label :date_mise_en_service %>
    <%= f.date_select :date_mise_en_service %>
  </div>

  <div class="field">
    <%= f.label :marque %>
    <%= f.collection_select :marque_id, Marque.order(:libelle).all, :id, :libelle  %>
  </div>

  <div class="field">
    <%= f.label :personne %>
    <%= f.collection_select :personne_id, Personne.order(:nom).all , :id, :nom_complet  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voitures/_voiture_view.html.erb
<p>
  <strong>Immatriculation:</strong>
  <%= voiture.immatriculation %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= voiture.couleur %>
</p>

<p>
  <strong>Modele:</strong>
  <%= voiture.modele %>
</p>

<p>
  <strong>Date mise en service:</strong>
  <%= voiture.date_mise_en_service %>
</p>

<p>
  <strong>Personne:</strong>
  <%= voiture.personne.try(:nom_complet)  %>
</p>

<p>
  <strong>Marque:</strong>
  <%= link_to voiture.marque.try(:libelle), marque_path(voiture)  %>
</p>

app/views/voitures/edit.html.erb
<h1>Editing Voiture</h1>

<%= render 'form', voiture: @voiture %>

<%= link_to 'Show', @voiture %> |
<%= link_to 'Back', voitures_path %>

app/views/voitures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voitures</h1>

<table>
  <thead>
    <tr>
      <th>Immatriculation</th>
      <th>Couleur</th>
      <th>Marque</th>
      <th>Modele</th>
      <th>Date mise en service</th>
      <th>Propriétaire</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voitures.each do |voiture| %>
      <tr>
        <td><%= voiture.immatriculation %></td>
        <td><%= voiture.couleur %></td>
        <td><%= voiture.modele %></td>
        <td><%= voiture.date_mise_en_service %></td>
        <td><%= voiture.personne.try(:nom_complet) %>
        <td><%= link_to 'Show', voiture %></td>
        <td><%= link_to 'Edit', edit_voiture_path(voiture) %></td>
        <td><%= link_to 'Destroy', voiture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voiture', new_voiture_path %>

app/views/voitures/new.html.erb
<h1>New Voiture</h1>

<%= render 'form', voiture: @voiture %>

<%= link_to 'Back', voitures_path %>

app/views/voitures/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'voiture_view', locals: {voiture:@voiture} %>

<%= link_to 'Edit', edit_voiture_path(@voiture) %> |
<%= link_to 'Back', voitures_path %>